### ISSUE TITLE
An exception occurs every time the inspector is invoked from a card screen.

### ISSUE THREAD

**Issue by Andrej-Adamenko** [hikaru-y/anki21-addon-ankiwebview-inspector#4]
If I ignored the error everything seemed to work fine.

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.43 (0fbae6bc) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-04-07 07:35:11

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 36, in cmd
  File "aqt\webview.py", line 135, in _onCmd
  File "aqt\webview.py", line 567, in _onBridgeCmd
AttributeError: 'NoneType' object has no attribute 'installEventFilter'

```

**Comment by hikaru-y** [comment]
Hi, thanks for the feedback.

I cannot reproduce the issue here. Does the error occur if you only enable this add-on?

Apart from the issue, in the current implementation of the add-on, if you run the "inspect" command on a webview in a window other than the main window, the inspector will appear in the main window, so the add-on is not practical for those windows. See #1 .

To improve this point, I am currently working on trying to make it possible to display the webview and the inspector side-by-side or stacked-vertically in those windows.  I haven't published it yet, but I've already made some improvements locally (see screenshots below), and hopefully I'll be able to release a new, improved version within a few months or so.

(Sorry for my bad English.)

![inspector_on_editor](https://user-images.githubusercontent.com/47855854/113902916-60248380-980b-11eb-90d1-0a3de2792e97.png)

![inspector_on_clayout](https://user-images.githubusercontent.com/47855854/113903031-7cc0bb80-980b-11eb-87cc-a3c92845af9a.png)

**Comment by Andrej-Adamenko** [comment]
The steps to reproduce the bug on my side were:
1. In the main Anki Window click on one of the decks and click Study Now. 
2. A card will be shown
3. Right click anywhere on the card
4. A context menu will appear with 2 options: `"Copy"` and `"Inspect"`
5. Click on `"Inspect"`

A window with the error message was shown (see the message above)

I reproduced the error several times in a row.

However I tried to reproduce it now and I could not. No error message was shown anymore. I do not know what has changed.

**Comment by hikaru-y** [comment]
I completely misunderstood the meaning of "card screen" in the title, sorry. I thought you were referring to the "card layout screen (card template editing screen)".

I guess the above error was probably caused by another add-on or Anki itself.

As you can see from the source code,
this add-on will
- add an `inspect` action to the right-click menu for the main window's webview(`mw.web`).
    - https://github.com/hikaru-y/anki21-addon-ankiwebview-inspector/blob/8a4ca14e10cee6537d80e4f04fd6c9a23be711fc/src/inspector.py#L40
    - https://github.com/hikaru-y/anki21-addon-ankiwebview-inspector/blob/8a4ca14e10cee6537d80e4f04fd6c9a23be711fc/src/inspector.py#L44-L45
- retrieve the web channel used by `mw.web._page` in order to share with inspector
    - https://github.com/hikaru-y/anki21-addon-ankiwebview-inspector/blob/8a4ca14e10cee6537d80e4f04fd6c9a23be711fc/src/inspector.py#L61

, but it will
- not change any attributes of `mw.web`
- not override any methods of `mw.web`
- not touch `_onBridgeCmd`
- not use `installEventFilter()` function

Therefore, I believe that this add-on is not likely to cause the error.
